USE AmazonDB;
-- 1) List all customers who have made purchases of more than $80.
SELECT -- It will select columns to show in output
    orders.user_id,
    SUM(orders.total_amount) AS total_spent,
    Users.name
FROM
    orders
INNER JOIN
    Users
ON 
    orders.user_id = Users.user_id
GROUP BY
    orders.user_id
HAVING
    SUM(orders.total_amount) > 80; -- we grouped by user_id before sum. It adds amounts for each user as group. If not for group, then we can use WHERE itself.
    
-- 2) Retrieve all orders placed in the last 280 days along with the customer name and email.
SELECT
	orders.user_id,
    orders.order_date,
    Users.name,
    Users.email
FROM
	orders
INNER JOIN
	Users
ON
	orders.user_id = Users.user_id
WHERE orders.order_date >= CURRENT_DATE - INTERVAL 280 DAY;

-- 3.Find the average product price for each category.
SELECT
	products.category,
	AVG(products.price) AS average_price
FROM  products
GROUP BY products.category;

-- 4. List all customers who have purchased a product from the category Electronics.
SELECT DISTINCT -- DISTINCT WILL SELECT UNIQUE VALUES BY REMOVING DUPLICATES
	Users.name,
    Users.email
FROM
	Users
INNER JOIN
	orders ON Users.user_id = orders.user_id
INNER JOIN
	OrderDetails ON orders.order_id = OrderDetails.order_id
INNER JOIN   
	products ON OrderDetails.product_id = products.product_id
WHERE products.category = 'Electronics';

-- 5.Find the total number of products sold and the total revenue generated for each product.
SELECT
	products.product_id,
    products.name,
    SUM(OrderDetails.quantity) AS no_of_products_sold,
    SUM(OrderDetails.quantity * products.price) AS total_revenue
FROM
	OrderDetails
INNER JOIN 
	products ON OrderDetails.product_id = products.product_id
GROUP BY OrderDetails.product_id;
	
-- 6.Update the price of all products in the Books category, increasing it by 10%.
SET SQL_SAFE_UPDATES =0;
UPDATE products
SET price = price + (price*10/100)
-- this also can be wriiten as SET price = price(1+0.1) (i.e) SET price = price(1.1)
WHERE category = 'Books';

SELECT * FROM products;

-- 7.Remove all orders that were placed before 2020.
SET SQL_SAFE_UPDATES =0;
DELETE FROM 
    orders
WHERE 
    order_date < '2020-01-01';
SELECT * FROM orders;

-- 8. Write a query to fetch the order details, including customer name, product name, and quantity, for orders placed on 2024-05-01.
SELECT
	Users.name AS User_name,
    products.name AS Product_name,
	orders.order_id,
    orders.order_date
FROM
	Users
INNER JOIN 
	orders ON Users.user_id = orders.user_id
INNER JOIN 
	OrderDetails ON orders.order_id =  OrderDetails.order_id
INNER JOIN 
	products ON OrderDetails.product_id = products.product_id
WHERE orders.order_date = '2024-05-01';
 
 -- 9. Fetch all customers and the total number of orders they have placed.
SELECT
	Users.name AS Customer_name,
    Users.email,
    COUNT(Orders.user_id) AS total_no_of_orders
FROM
	Users
LEFT JOIN
	Orders ON Users.user_id = Orders.user_id
    GROUP BY Users.user_id;
    
-- 10. Retrieve the average rating for all products in the Electronics category.
ALTER TABLE products
ADD rating INT CHECK (rating BETWEEN 1 and 5);

UPDATE products
SET rating = 4
WHERE product_id = 1;

UPDATE products
SET rating = 3
WHERE product_id = 2;

UPDATE products
SET rating = 4
WHERE product_id = 3;

UPDATE products
SET rating = 5
WHERE product_id = 4;

UPDATE products
SET rating = 5
WHERE product_id = 5;

SELECT
	products.category,
    AVG(products.rating) AS avarage_rating
FROM products
where category = 'Electronics';

    
SELECT * FROM products;

-- 11.List all customers who purchased more than 1 units of any product, including the product name and total quantity purchased.
SELECT
	Users.user_id,
    Users.name AS Customer_name,
    products.name AS Product_name,
    SUM(OrderDetails.quantity) AS total_quantity
FROM
	Users
INNER JOIN
	Orders ON Users.user_id = Orders.user_id
INNER JOIN
	OrderDetails ON Orders.order_id = OrderDetails.order_id
INNER JOIN 
	products ON OrderDetails.product_id = products.product_id
    
GROUP BY Users.user_id,products.product_id    
HAVING SUM(OrderDetails.quantity) > 1;

-- 12.Find the total revenue generated by each category along with the category name.
SELECT
	products.category,
    SUM(products.price * OrderDetails.quantity) AS total_revenue
FROM
	orders
INNER JOIN
	OrderDetails ON orders.order_id = OrderDetails.order_id
INNER JOIN
	products ON  OrderDetails.product_id = products.product_id
GROUP BY
	products.category;
	

    
